### ISSUE TITLE
Velux Gateway communication hangs with TLS error

### ISSUE THREAD

**Issue by manssebas** [clesser/labs.logicmodules#1]
After upgrading to version 1.0.2  of the logic node Velux KLF-200 and Gira X1 version to 2.8.874.0 we encounter the following problem:
- sometimes between 1 and 3 day we fail to communicate with the gateway with the following error;

Node 'Velux KLF-200 Gateway' on page 'Velux'
An exception occurred during processing of node '7c227b3a-56da-45a7-b3b4-5c94458f92dd' of type 'neleo_com.Logic.Bridges.Velux.VeluxGateway'. The exception was:

System.IO.IOException: Cannot write application data on closed/failed TLS connection
  at Org.BouncyCastle.Crypto.Tls.TlsProtocol.WriteData (System.Byte[] buf, Int32 offset, Int32 len) [0x00000] in <filename unknown>:0 
  at Org.BouncyCastle.Crypto.Tls.TlsStream.Write (System.Byte[] buf, Int32 off, Int32 len) [0x00000] in <filename unknown>:0 
  at neleo_com.Logic.Bridges.Velux.Klf200SocketBc.SendRequest (neleo_com.Logic.Bridges.Velux.Klf200Datagram datagram) [0x00000] in <filename unknown>:0 
  at neleo_com.Logic.Bridges.Velux.Klf200Gateway.RequestState () [0x00000] in <filename unknown>:0 
  at neleo_com.Logic.Bridges.Velux.VeluxGateway.Execute () [0x00000] in <filename unknown>:0 
  at LogicModule.Engine.Core.NodeRuntime.Execute () [0x00000] in <filename unknown>:0 
  at LogicModule.Engine.Core.GraphRuntime.RunNodeCodeSafely (System.Action action, INodeRuntimeInternal node, System.String nodeKey, System.String port, Boolean disable, System.String outOfRangeMessage, System.String exceptionMessage) [0x00000] in <filename unknown>:0 

To the gateway there are connected 17 Velux devices. We also request state once in 1 minute, we will try to disable this and see if the error from above reapers.

**Comment by clesser** [comment]
Thank you for the information. I will review the system during the holidays to determine if further improvements can be made (e.g. reconnect to KLF-200 after the IOException has been detected - which has some implications to the internal logic).

But let me share some background information which may help you to stabilize your setup:

The KLF-200 needs a constant connection with the X1 to receive requests and push updates. Therefore, the logic module maintains this connection by sending a keep-alive message every 7 minutes to prevent auto-closing after 15 minutes of inactivity.
If the logic module detects a lost connection, it will typically reestablish it in most cases (various issues such as timeouts or network problems may result in the loss of an established connection). It is not necessary to ping the gateway regularly. The system will automatically recognize updates from shutters, blinds, and other devices, eliminating the need for manual polling.

The KLF-200 can handle a limited number of requests within a specific time. Sending an excessive number of messages may disrupt communication between devices, including between the KLF-200 and X1. I therefore use the standard logic module to delay messages to prevent sending too many messages to the KLF-200. I chose not to implement this in my module because I would then also need to implement some prioritization logic to allow bypassing the internal queue as well e.g. for STOP signals).

I recommend following the split architecture approach, which involves using one logic sheet for the gateway and its input/output connectors, along with a separate sheet for each device as outlined here: [[neleo.labs] X1 Velux KLF Bausteine - Gateway - Hilfe](https://x1.labs.neleo.com/logic.bridges.velux/gatewayconnector/index.html)). There is no need to manually trigger any updates, as they will be delivered automatically as long as the connection between the KLF-200 and X1 remains stable.

Note: I have two types of devices that are connected to my KLF-200 (10 in total). Two of them do not report their state back to KLF-200 unless any action has been carried out. If you do not get the state of a device - this might be the reason, too.
